### ISSUE TITLE
Enhancement Request: use Blizzard AddOn Compartment (proposed resolution in PR15)

### ISSUE THREAD

**Issue by JPEscher** [MMOSimca/BattlePetBreedID#14]
from https://legacy.curseforge.com/wow/addons/battle_pet_breedid/issues/29
hi team, i noticed a lot of my addons use https://warcraft.wiki.gg/wiki/Addon_compartment

I was wondering if it might be a better way to get to the add on section than opening the options and going to the addons tab

i tried this and it works, so i will make a pr and you can decide :)
```
local mouseButtonNote = "\nEasily display your pets BreedIDs!";
AddonCompartmentFrame:RegisterAddon({
	text = addonname,
	icon = "Interface/Icons/petjournalportrait.blp",
	notCheckable = true,
	func = function(button, menuInputData, menu)
		Settings.OpenToCategory(addonname)
	end,
	funcOnEnter = function(button)
		MenuUtil.ShowTooltip(button, function(tooltip)
			tooltip:SetText(addonname .. mouseButtonNote)
		end)
	end,
	funcOnLeave = function(button)
		MenuUtil.HideTooltip(button)
	end,
})
```
added to Interface/AddOns/BattlePetBreedID/BattlePetBreedID.lua

![image](https://github.com/user-attachments/assets/3069f470-9882-43dd-9c38-35209429cf07)

how i found the image: https://www.wowhead.com/icons
if direct link works: https://www.wowhead.com/icons/name:petj

**Comment by JPEscher** [comment]
$ git push --set-upstream origin addOnsCompartmentStarter
ERROR: Permission to MMOSimca/BattlePetBreedID.git denied to JPEscher.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by JPEscher** [comment]
hope my playing at least helps

**Comment by JPEscher** [comment]
me trying to help
https://github.com/MMOSimca/BattlePetBreedID/pull/15

**Comment by MMOSimca** [comment]
Thanks for this! Merged.
