### ISSUE TITLE
Errors Following 11.0.2 Update

### ISSUE THREAD

**Issue by swotam** [MMOSimca/BattlePetBreedID#16]
Experiencing the following error after the 11.0.2 update even if no other addons are loaded:

4x BattlePetBreedID/BattlePetBreedID.lua:517: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@BattlePetBreedID/BattlePetBreedID.lua"]:517: in function <BattlePetBreedID/BattlePetBreedID.lua:460>

Locals:
self = BPBID_Events {
}
event = "ADDON_LOADED"
name = "BattlePetBreedID"
(*temporary) = "v1.29.1"
(*temporary) = nil
(*temporary) = "BattlePetBreedID"
(*temporary) = "Version"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
addonname = "BattlePetBreedID"
internal = <table> {
 cacheTime = true
 resultsCache = <table> {
 }
 rarityCache = <table> {
 }
 MAX_BREEDS = 10
 breedCache = <table> {
 }
 speciesCache = <table> {
 }
}
PJHooked = false

**Comment by niftyneato** [comment]
Changing GetAddOnMetadata to C_AddOns.GetAddOnMetadata on line 517 fixed it for me. I don't know if  there are other issues but it shuts thats error up when the addon loads.

**Comment by swotam** [comment]
> Changing GetAddOnMetadata to C_AddOns.GetAddOnMetadata on line 517 fixed it for me. I don't know if there are other issues but it shuts thats error up when the addon loads.

I can confirm that manually making this change to the existing BattlePetBreedID.lua resolves the issue
