### ISSUE TITLE
Pet Journal Search Bar issue

### ISSUE THREAD

**Issue by j-xenman** [MMOSimca/BattlePetBreedID#19]
1. install/activate the addon
2. type something into the Pet Journal search bar
3. hover over the selected pet card's pet icon for a tooltip (it doesn't matter if the pet card was for a pet selected before or after the search)
4. the search results are negated and rolled back to the standard alphabetical pet list, even though the search query remains in the bar

i installed version v1.31.1, the only other addon i have installed is TomTom, but i disabled it, to no effect
![зображення](https://github.com/user-attachments/assets/1dde5d95-ce20-4efb-a3df-5144e5fc603c)
![зображення](https://github.com/user-attachments/assets/8ff2ac66-3d67-4e5a-b23c-395d8de00737)

**Comment by MMOSimca** [comment]
Thanks for the detailed bug report!

I've replicated this behavior. It looks like there's an OnEnter hook of some kind for PetJournalPetCardPetInfo that's doing this.

Will investigate further and see if I can eliminate it without harming other functionality.

**Comment by MMOSimca** [comment]
This ended up being the fault of the new-ish "Collected" tooltip code, but I found and tested a workaround that should have almost no side effects.

Implemented in v1.31.2.
