### ISSUE TITLE
10.0 Dragonflight PTR error

### ISSUE THREAD

**Issue by yoshimo** [MMOSimca/BattlePetBreedID#3]
I get this error :

`1x Interface/AddOns/BattlePetBreedID/OptionsPanel.lua:81: attempt to index global 'InterfaceOptionsFramePanelContainer' (a nil value)
[string "@Interface/AddOns/BattlePetBreedID/OptionsPanel.lua"]:81: in main chunk

Locals:
addonname = "BattlePetBreedID"
internal = <table> {
 cacheTime = true
 CacheAllPets = <function> defined @Interface/AddOns/BattlePetBreedID/BattlePetBreedID.lua:331
 resultsCache = <table> {
 }
 Hook_PJTLeave = <function> defined @Interface/AddOns/BattlePetBreedID/BreedTooltips.lua:505
 CalculateBreedID = <function> defined @Interface/AddOns/BattlePetBreedID/BattlePetBreedID.lua:48
 Hook_ArkInventory = <function> defined @Interface/AddOns/BattlePetBreedID/BreedTooltips.lua:513
 Hook_PJTEnter = <function> defined @Interface/AddOns/BattlePetBreedID/BreedTooltips.lua:461
 rarityCache = <table> {
 }
 MAX_BREEDS = 10
 breedCache = <table> {
 }
 RetrieveBreedName = <function> defined @Interface/AddOns/BattlePetBreedID/BattlePetBreedID.lua:262
 speciesCache = <table> {
 }
}
Options = Frame {
 0 = <userdata>
 name = "Battle Pet BreedID"
}
lastcheckbox = nil
CreateFont = <function> defined @Interface/AddOns/BattlePetBreedID/OptionsPanel.lua:52
CreateCheckbox = <function> defined @Interface/AddOns/BattlePetBreedID/OptionsPanel.lua:70
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'InterfaceOptionsFramePanelContainer' (a nil value)"
`

**Comment by MMOSimca** [comment]
Yeah, the addon options panel needs to be redone for 10.0. Working on that tonight.

**Comment by MMOSimca** [comment]
Fixed in v1.22.1.
