### ISSUE TITLE
Incorrect breed ID

### ISSUE THREAD

**Issue by quvalek** [MMOSimca/BattlePetBreedID#4]
I was doing some pet caching and noticed this breed wasn't showing as a posible breed.

<img alt="image" src="https://user-images.githubusercontent.com/105289881/197268781-6c9a65dc-6821-43ad-ac65-9cbfe41d8908.png">

After capturing it, it turned out to be a B/B instead of H/S.

**Comment by MMOSimca** [comment]
Was this on Live (9.2.7) or in PTR/Beta (10.0)?

**Comment by MMOSimca** [comment]
Found the issue.

Wild pets under level 6 have a different power penalty (40% instead of the usual 25%).

Fixed in v1.22.6.
