### ISSUE TITLE
Pet breed showing as ???

### ISSUE THREAD

**Issue by zeenk** [MMOSimca/BattlePetBreedID#8]
First time I've seen this so not sure if it's something special about this pet or just some bug?

![2024-03-08_03-01-14](https://github.com/MMOSimca/BattlePetBreedID/assets/68170439/57dddc6b-be28-4e08-a378-6a796e23193c)

**Comment by zeenk** [comment]
Ah, found the answer

![2024-03-08_03-25-55](https://github.com/MMOSimca/BattlePetBreedID/assets/68170439/b03de052-3c83-4244-96cc-faabf6adac7d)

**Comment by MMOSimca** [comment]
Yeah, sorry, this is unfixable as long as the addon has to calculate breed mathematically. If the stats are the same, it can't tell.

If Blizzard would give us decimals (at least API-side), that would also fix it, but they round the stats internally before showing us..
